{% set python_min = python_min|default("3.7") %}
{% set name = "jedi" %}
{% set version = "0.19.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4770dc3de41bde3966b02eb84fbcf557fb33cce26ad23da12c742fb50ecb11f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - parso >=0.8.3,<0.9.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - jedi
    - jedi.api
    - jedi.common
    - jedi.inference
    - jedi.inference.compiled
    - jedi.inference.compiled.subprocess
    - jedi.inference.gradual
    - jedi.inference.value
    - jedi.plugins
  commands:
    - python -m pip check

about:
  home: https://github.com/davidhalter/jedi/
  license: MIT
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE.txt
    - jedi/third_party/django-stubs/LICENSE.txt
    - jedi/third_party/typeshed/LICENSE
  summary: An autocompletion tool for Python that can be used for text editors.
  description: |
    Jedi is a static analysis tool for Python that can be used in IDEs/editors.
    Its historic focus is autocompletion, but does static analysis for now as
    well. Jedi is fast and is very well tested. It understands Python on a
    deeper level than all other static analysis frameworks for Python.
  dev_url: https://github.com/davidhalter/jedi/
  doc_url: http://jedi.readthedocs.io/en/latest/
  doc_source_url: https://github.com/davidhalter/jedi/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - goanpeca
    - asmeurer
    - nehaljwani
    - ocefpaf
